### DISCUSSION TITLE
Backtesting using Ansible

### DISCUSSION THREAD

**Discussion by kenorb** [EA31337/ansible-role-mt-runner#3] [Show and tell]
To backtest EA using Ansible (the complete solution is still in progress), you can use [ansible-role-mt-runner](https://github.com/EA31337/ansible-role-mt-runner) Ansible role to run the test.

To run roles, you need to install Ansible (`pip install ansible`) and have some basic understanding how does it work.

The mt-runner role depends on the following other roles (depending on the operating system):
- ansible-role-wine to install Wine (only applicable if you're running it on Linux)
- ansible-role-xvfb to install Xvfb (only applicable if you're running it on Linux)
- ansible-role-metatrader (to install MetaTrader 4 or 5 using AHK verbs)

## Install Wine

In below example, you can find out how to install Wine (Linux only) using provided Ansible role (this assumes you've already Ansible installed).

Install Wine role via Ansible Galaxy (this will install role in `~/.ansible/roles`):

```
ansible-galaxy install git+https://github.com/EA31337/ansible-role-wine.git
ansible-galaxy install git+https://github.com/EA31337/ansible-role-xvfb.git
```

Create the following playbook file (customize as needed), e.g. `wine.yml`:

```
---
- hosts: localhost
  roles:
    - role: ansible-role-wine
      vars:
        wine_install_7pzip: true
        wine_install_winetricks: true
```

To play it on localhost, navigate to repository directory and run:

    ansible-playbook -i "localhost," -c local wine.yml

To run on remote, create Ansible hosts file and run on `hosts: all` (check Ansible docs pages for more details).

## Run test

Install MetaTrader role by:

```
ansible-galaxy install git+https://github.com/EA31337/ansible-role-metatrader.git
```

To run backtest, create the following playbook (`ea-tester.yml`):

```
---
- hosts: localhost
  roles:
    - role: ansible-role-metatrader
      vars:
        wine_install_7pzip: true
        wine_install_winetricks: true
```

Then run as:

```
!ansible-playbook -i "localhost," -c local ea-tester.yml
```

----

Check the demo at https://colab.research.google.com/drive/1ybsqnVANuiJBdnza47e9VRIYFK4E1xKZ?usp=sharing
