### ISSUE TITLE
error non zero return code when running metatrader 5/terminal64.exe

### ISSUE THREAD

**Issue by NirobNabil** [EA31337/ansible-role-mt-runner#8]
As instructed in https://github.com/EA31337/ansible-role-metatrader/issues/6, I commented out the opensymbols font download. And the metatrader installation completed successfully. But Then the following error occurred. 

I checked that `main.yml:12` refers to `mt_runner_mt_files` defined in `vars/main.yml` But for some reason the variable wasnt fetched(?). I hardcoded the value `terminal64.exe` in place of the variable reference and the step completed successfully but then the second error occurred which i haven't been able to debug yet.

I'm running `ansible-playbook -i "localhost," -c local test.yml -vvv` to run the role 
`test.yml` contents:

#
**It will be really helpful if you can provide a running demo with step by step instruction.** 


```
---
- hosts: all                                                                                                                                                                                                                                   
  gather_facts: yes                                                                                                                                                                                                                            
  become: yes                                                                                                                                                                                                                                  
  roles:                                                                                                                                                                                                                                       
   - mt-runner 
```

Error output 1
```
TASK [mt-runner : Query MT platform path] 
**************************************************************************************************************************
*************************************************************************
task path: /home/ubuntu/.ansible/roles/mt-runner/tasks/main.yml:12                                                                                                                                                                           
fatal: [localhost]: FAILED! => {                                                                                                                                                                                                                 
  "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '5'. 
  'dict object' has no attribute '5'\n\nThe error appears to be in '/home/ubuntu/.ansible/roles/mt-runner/tasks/main.yml': 
  line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line 
  appears to be:\n\n    - winbind\n- name: Query MT platform path\n  ^ here\n"                                            
}    
```

Error output 2
```
fatal: [localhost]: FAILED! => {
  "changed": false,
  "cmd": "wine '/root/.wine/dosdevices/c:/Program Files/MetaTrader 5/terminal64.exe' \"/config:tester.ini\"",
  "delta": "0:00:13.430257",
  "end": "2023-10-15 20:27:29.454976",
  "invocation": {
    "module_args": {
      "_raw_params": "wine '/root/.wine/dosdevices/c:/Program Files/MetaTrader 5/terminal64.exe' \"/config:tester.ini\"",
      "_uses_shell": true,
      "argv": null,
      "chdir": "/root/.wine/dosdevices/c:/Program Files/MetaTrader 5",
      "creates": null,
      "executable": null,
      "removes": null,
      "stdin": null,
      "stdin_add_newline": true,
      "strip_empty_ends": true
    }
  },
  "msg": "non-zero return code",
  "rc": 190,
  "start": "2023-10-15 20:27:16.024719",
  "stderr": "0048:err:ole:start_rpcss Failed to start RpcSs service\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031ad20\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0466 wp=00000000 lp=0031ad20\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031a5e0\n00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 
lp=0031a5e0\n00cc:err:toolbar:Toolbar 
... ... ...
"00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031e2d0",                                                                                                                                                               
"00cc:err:toolbar:ToolbarWindowProc unknown msg 0465 wp=00000000 lp=0031e2d0",                                                                                                                                                               
"00cc:err:ntdll:RtlLeaveCriticalSection section 00000001421B0520 is not acquired"                                                                                                                                                        
],                                                                                                                                                                                                                                           
"stdout": "",                                                                                                                                                                                                                                
"stdout_lines": []                                                                                                                                                                                                                       
}    

```
